version: '2'
services:
  db:
    container_name: djangotutorial_db
    image: postgres:9.6.0
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: djangotutorial_web
    build: .
    command: dockerize -wait tcp://db:5432 ./scripts/web/start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST
      - DB_PASSWORD
volumes:
  postgres_data:
